from colorama import *

print(Fore.BLUE, Back.GREEN)
print("**************************************")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("*                                    *")
print("**************************************")
